name: absher
description: A new Flutter project.

version: 0.0.01+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.6.0
  hive_flutter: ^1.1.0
  dio: ^5.1.2
  dartz: ^0.10.1
  flutter_svg:
  carousel_slider: ^4.2.1
  overlay_support: ^2.1.0
  sms_autofill: ^2.3.0
  flutter_spinkit: ^5.2.0
  shimmer:
  package_info_plus: ^4.0.0
  lottie:
  extended_image:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
#  assets:
#    - assets/
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Light.ttf
          weight: 300
        - asset: fonts/Cairo-Regular.ttf
          weight: 400
        - asset: fonts/Cairo-Medium.ttf
          weight: 500
        - asset: fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: fonts/Cairo-Bold.ttf
          weight: 700


